development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: huodong_dev
  pool: 5
  host: 127.0.0.1
  username: root
  password: "password"
  # socket: /tmp/mysql.sock

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: huodong_production
  pool: 5
  username: root
  password: "password"


production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: huodong_test
  pool: 5
  username: root
  password: "password"